language: python
python:
- 3.5-dev
sudo: required
services:
  - docker
cache:
  directories:
  - eggs
before_install:
- docker-compose -f docker-compose-dev.yml up -d 
install:
- python bootstrap-buildout.py
- bin/buildout -t 3
- docker ps -a
- pip install flake8
- pip install coverage==4.0.3
- sleep 15
script:
- bin/py.test -s --cov=plone.server -v --cov-report term-missing src 
- bin/code-analysis
after_script:
  - docker-compose stop
  - docker-compose rm -f
after_success:
- coveralls
- cat .coverage
