language: python
python:
- 3.5
sudo: required
services:
  - docker
cache:
  directories:
  - eggs
before_install:
- docker-compose -f docker-compose-dev.yml up -d 
install:
- python bootstrap-buildout.py
- bin/buildout -t 3
- docker ps -a
- sleep 15
script:
- bin/py.test -s --cov=plone.server src
- bin/code-analysis
after_script:
  - docker-compose stop
  - docker-compose rm -f